apiVersion: apps/v1
kind: Deployment
metadata:
  name: irrirat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irrirat
  template:
    metadata:
      labels:
        app: irrirat
    spec:
      containers:
      - image: okteto.dev/irrirat:latest
        name: irrirat
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/L-html.zip"
        - name: Vless_UUID
          value: "7f33736b-7873-4693-91aa-b9f0f1022de8"
        - name: Vless_Path
          value: "/7f33736b-7873-4693-91aa-b9f0f1022de8-vless"
        - name: Vmess_UUID
          value: "7f33736b-7873-4693-91aa-b9f0f1022de8"
        - name: Vmess_Path
          value: "/7f33736b-7873-4693-91aa-b9f0f1022de8-vmess"
        - name: Share_Path
          value: "/zeredfk"
